LOCAL_PATH := $(call my-dir)
3RD_PARTY_RELATIVE_PATH := ../../../../../../3rdparty/
3RD_PARTY_SUPERPOWERED_RELATIVE_PATH := $(3RD_PARTY_RELATIVE_PATH)/Superpowered/

include $(CLEAR_VARS)
LOCAL_MODULE := Superpowered
ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
	LOCAL_SRC_FILES := $(3RD_PARTY_SUPERPOWERED_RELATIVE_PATH)/libSuperpoweredAndroidarmeabi-v7a.a
else ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
	LOCAL_SRC_FILES := $(3RD_PARTY_SUPERPOWERED_RELATIVE_PATH)/libSuperpoweredAndroidarm64-v8a.a
else ifeq ($(TARGET_ARCH_ABI),x86)
	LOCAL_SRC_FILES := $(3RD_PARTY_SUPERPOWERED_RELATIVE_PATH)/libSuperpoweredAndroidX86.a
else ifeq ($(TARGET_ARCH_ABI),x86_64)
	LOCAL_SRC_FILES := $(3RD_PARTY_SUPERPOWERED_RELATIVE_PATH)/libSuperpoweredAndroidX86_64.a
endif

include $(PREBUILT_STATIC_LIBRARY)

PROJECT_ROOT_PATH := $(LOCAL_PATH)/../../../../../../
CORE_RELATIVE_PATH := ../../../../../../core/
CORE_FRAMEWORK_RELATIVE_PATH := $(CORE_RELATIVE_PATH)/framework/
CORE_FRAMEWORK_ENTITY_RELATIVE_PATH := $(CORE_FRAMEWORK_RELATIVE_PATH)/entity/
CORE_FRAMEWORK_MATH_RELATIVE_PATH := $(CORE_FRAMEWORK_RELATIVE_PATH)/math/
CORE_FRAMEWORK_SOUND_RELATIVE_PATH := $(CORE_FRAMEWORK_RELATIVE_PATH)/sound/
CORE_FRAMEWORK_STATE_RELATIVE_PATH := $(CORE_FRAMEWORK_RELATIVE_PATH)/state/
CORE_FRAMEWORK_UI_RELATIVE_PATH := $(CORE_FRAMEWORK_RELATIVE_PATH)/ui/
CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH := $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/opengl/
CORE_FRAMEWORK_UTIL_RELATIVE_PATH := $(CORE_FRAMEWORK_RELATIVE_PATH)/util/
CORE_GAME_RELATIVE_PATH := $(CORE_RELATIVE_PATH)/game/
CORE_GAME_UI_RELATIVE_PATH := $(CORE_GAME_RELATIVE_PATH)/ui/
CORE_GAME_UI_OPENGL_RELATIVE_PATH := $(CORE_GAME_UI_RELATIVE_PATH)/opengl/
CORE_GAME_UI_OPENGL_ANDROID_RELATIVE_PATH := $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/android/

include $(CLEAR_VARS)

LOCAL_MODULE    := game
LOCAL_CFLAGS    := -Wall -Wextra -DNG_OPENGL -DNG_ANDROID -DGL_GLEXT_PROTOTYPES=1 -O3 -fsigned-char

# Android
LOCAL_SRC_FILES := platform_asset_utils.c
LOCAL_SRC_FILES += game.cpp
LOCAL_SRC_FILES += sound_manager.cpp

# Game Framework
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/framework/
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/framework/entity/
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/framework/math/
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/framework/sound/superpowered/
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/framework/state/
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/framework/ui/
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/framework/ui/opengl/
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/framework/util/

LOCAL_SRC_FILES += $(CORE_FRAMEWORK_ENTITY_RELATIVE_PATH)/Entity.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_ENTITY_RELATIVE_PATH)/EntityManager.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_ENTITY_RELATIVE_PATH)/GridLockedPhysicalEntity.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_ENTITY_RELATIVE_PATH)/PhysicalEntity.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_MATH_RELATIVE_PATH)/Circle.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_MATH_RELATIVE_PATH)/Line.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_MATH_RELATIVE_PATH)/OverlapTester.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_MATH_RELATIVE_PATH)/Rectangle.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_MATH_RELATIVE_PATH)/Triangle.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_MATH_RELATIVE_PATH)/Vector2D.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_SOUND_RELATIVE_PATH)/superpowered/SuperpoweredSound.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_SOUND_RELATIVE_PATH)/superpowered/SuperpoweredSoundManager.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/Animation.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/CircleBatcher.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/DummyGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/Font.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/GpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/LineBatcher.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/RectangleBatcher.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/Renderer.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/SinWaveTextureGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/SpriteBatcher.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/Text.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/TextureRegion.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/TouchEvent.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_RELATIVE_PATH)/TransitionGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/asset_utils.c
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/image.c
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/ColorProgram.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/FramebufferToScreenProgram.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/OpenGLCircleBatcher.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/OpenGLFramebufferObfuscationGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/OpenGLFramebufferToScreenGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/OpenGLGeometryGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/OpenGLRenderer.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/OpenGLLineBatcher.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/OpenGLManager.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/OpenGLRectangleBatcher.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/OpenGLSinWaveTextureGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/OpenGLSpriteBatcher.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/OpenGLTextureGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/SinWaveTextureProgram.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/platform_file_utils.c
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/shader.c
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/texture.c
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/TextureProgram.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UI_OPENGL_RELATIVE_PATH)/TransitionProgram.cpp
LOCAL_SRC_FILES += $(CORE_FRAMEWORK_UTIL_RELATIVE_PATH)/RTTI.cpp

# Game
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/game/
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/game/ui/
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/game/ui/opengl/
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/core/game/ui/opengl/android/

LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/Background.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/CollectibleItem.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/CountHissWithMina.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/DustCloud.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/EndBossSnake.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/Enemy.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/EnemySpirit.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/ExitGround.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/ExitGroundCover.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/ForegroundCoverObject.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/ForegroundObject.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/Game.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/GameMarker.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/Ground.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/Hole.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/HoleCover.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/Jon.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/JonFormState.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/MidBossOwl.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/Midground.cpp
LOCAL_SRC_FILES += $(CORE_GAME_RELATIVE_PATH)/UnknownEntity.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/Assets.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/AssetsMapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/BatPanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/Chapter1Level10.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/Chapter1Level21.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/ConfirmExitPanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/ConfirmResetPanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/CutscenePanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/EndBossSnakeTextureGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/FramebufferRadialBlurGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameButton.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameScreen.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameScreenComingSoon.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameScreenLevelEditor.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameScreenLevels.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameScreenOpeningCutscene.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameScreenSpriteTester.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameScreenState.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameScreenTitle.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameScreenTransitions.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameScreenWorldMap.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/GameTracker.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/LevelEditorActionsPanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/LevelEditorEntitiesPanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/LevelSelectorPanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/OffsetPanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/PointTransitionGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/ShockwaveTextureGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/SnakeDeathTextureGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/SpriteTesterActionsPanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/SpriteTesterEntitiesPanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/TextureSelectorPanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/TitlePanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/TransDeathGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/TrashCan.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_RELATIVE_PATH)/WorldMapPanel.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/OpenGLEndBossSnakeTextureGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/OpenGLFadeScreenGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/OpenGLFramebufferTintGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/OpenGLFramebufferRadialBlurGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/OpenGLGameScreen.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/OpenGLPointTransScreenGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/OpenGLShockwaveTextureGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/OpenGLSnakeDeathTextureGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/OpenGLTransDeathGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/OpenGLTransScreenGpuProgramWrapper.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/PointTransitionProgram.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/ShockwaveTextureProgram.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/SnakeDeathTextureProgram.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_RELATIVE_PATH)/TransDeathProgram.cpp
LOCAL_SRC_FILES += $(CORE_GAME_UI_OPENGL_ANDROID_RELATIVE_PATH)/AndroidOpenGLGameScreen.cpp

# 3rd Party
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/3rdparty/Superpowered/
LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/3rdparty/Superpowered/AndroidIO/
LOCAL_SRC_FILES += $(3RD_PARTY_SUPERPOWERED_RELATIVE_PATH)/AndroidIO/SuperpoweredAndroidAudioIO.cpp

LOCAL_C_INCLUDES += $(PROJECT_ROOT_PATH)/3rdparty/
LOCAL_STATIC_LIBRARIES := libpng Superpowered
LOCAL_LDLIBS := -lGLESv2 -landroid -lOpenSLES

include $(BUILD_SHARED_LIBRARY)

$(call import-add-path, $(PROJECT_ROOT_PATH)/3rdparty)
$(call import-module, libpng)