//
//  GameConstants.h
//  nosfuratu
//
//  Created by Stephen Gowen on 5/13/14.
//  Copyright (c) 2017 Noctis Games. All rights reserved.
//

#ifndef __nosfuratu__GameConstants__
#define __nosfuratu__GameConstants__

//// VERSION ////

#define VERSION_MAJOR 1
#define VERSION_MINOR 2
#define VERSION_BUILD 5

//// Requested Action Definitions ////

#define REQUESTED_ACTION_UPDATE 0
#define REQUESTED_ACTION_DISPLAY_INTERSTITIAL_AD 1
#define REQUESTED_ACTION_SUBMIT_SCORE_TO_LEADERBOARD 2
#define REQUESTED_ACTION_SUBMIT_AND_DISPLAY_SCORE_TO_LEADERBOARD 3
#define REQUESTED_ACTION_UNLOCK_ACHIEVEMENT 4
#define REQUESTED_ACTION_DISPLAY_LEADERBOARDS 5
#define REQUESTED_ACTION_DISPLAY_ACHIEVEMENTS 6
#define REQUESTED_ACTION_SIGN_IN 7
#define REQUESTED_ACTION_SIGN_OUT 8

//// Sound Definitions ////

#define SOUND_ID_NONE 0
#define SOUND_ID_COLLECT_CARROT 1
#define SOUND_ID_COLLECT_GOLDEN_CARROT 2
#define SOUND_ID_DEATH 3
#define SOUND_ID_FOOTSTEP_LEFT_GRASS 4
#define SOUND_ID_FOOTSTEP_RIGHT_GRASS 5
#define SOUND_ID_FOOTSTEP_LEFT_CAVE 6
#define SOUND_ID_FOOTSTEP_RIGHT_CAVE 7
#define SOUND_ID_JUMP_SPRING 8
#define SOUND_ID_LANDING_GRASS 9
#define SOUND_ID_LANDING_CAVE 10
#define SOUND_ID_SNAKE_DEATH 11
#define SOUND_ID_TRIGGER_TRANSFORM 12
#define SOUND_ID_CANCEL_TRANSFORM 13
#define SOUND_ID_COMPLETE_TRANSFORM 14
#define SOUND_ID_JUMP_SPRING_HEAVY 15
#define SOUND_ID_JON_RABBIT_JUMP 16
#define SOUND_ID_JON_VAMPIRE_JUMP 17
#define SOUND_ID_JON_RABBIT_DOUBLE_JUMP 18
#define SOUND_ID_JON_VAMPIRE_DOUBLE_JUMP 19
#define SOUND_ID_JON_VAMPIRE_GLIDE 20
#define SOUND_ID_MUSHROOM_BOUNCE 21
#define SOUND_ID_JON_BURROW_ROCKSFALL 22
#define SOUND_ID_SPARROW_FLY 23
#define SOUND_ID_SPARROW_DEATH 24
#define SOUND_ID_TOAD_DEATH 25
#define SOUND_ID_TOAD_EAT 26
#define SOUND_ID_SAW_GRIND 27
#define SOUND_ID_FOX_BOUNCED_ON 28
#define SOUND_ID_FOX_STRIKE 29
#define SOUND_ID_FOX_DEATH 30
#define SOUND_ID_WORLD_1_LOOP_INTRO 31
#define SOUND_ID_MID_BOSS_LOOP_INTRO 32
#define SOUND_ID_MID_BOSS_SWOOP_DOWN 33
#define SOUND_ID_MID_BOSS_TREE_SMASH 34
#define SOUND_ID_MID_BOSS_DEATH 35
#define SOUND_ID_SCREEN_TRANSITION 36
#define SOUND_ID_SCREEN_TRANSITION_2 37
#define SOUND_ID_LEVEL_COMPLETE 38
#define SOUND_ID_TITLE_LIGHTNING_1 39
#define SOUND_ID_TITLE_LIGHTNING_2 40
#define SOUND_ID_ABILITY_UNLOCK 41
#define SOUND_ID_BOSS_LEVEL_CLEAR 42
#define SOUND_ID_LEVEL_CLEAR 43
#define SOUND_ID_LEVEL_SELECTED 44
#define SOUND_ID_RABBIT_DRILL 45
#define SOUND_ID_SNAKE_JUMP 46
#define SOUND_ID_VAMPIRE_DASH 47
#define SOUND_ID_BOSS_LEVEL_UNLOCK 48
#define SOUND_ID_RABBIT_STOMP 49
#define SOUND_ID_END_BOSS_LOOP_INTRO 50
#define SOUND_ID_BUTTON_CLICK 51
#define SOUND_ID_LEVEL_CONFIRMED 52
#define SOUND_ID_BAT_POOF 53
#define SOUND_ID_CHAIN_SNAP 54
#define SOUND_ID_END_BOSS_SNAKE_MOUTH_OPEN 55
#define SOUND_ID_END_BOSS_SNAKE_CHARGE_CUE 56
#define SOUND_ID_END_BOSS_SNAKE_CHARGE 57
#define SOUND_ID_END_BOSS_SNAKE_DAMAGED 58
#define SOUND_ID_END_BOSS_SNAKE_DEATH 59
#define SOUND_ID_SPIKED_BALL_ROLLING 60
#define SOUND_ID_ABSORB_DASH_ABILITY 61
#define SOUND_ID_FOOTSTEP_LEFT_WOOD 62
#define SOUND_ID_FOOTSTEP_RIGHT_WOOD 63
#define SOUND_ID_LANDING_WOOD 64
#define SOUND_ID_COLLECT_BIG_CARROT 65
#define SOUND_ID_COLLECT_VIAL 66

#define SOUND_COLLECT_CARROT "sound_001"
#define SOUND_COLLECT_GOLDEN_CARROT "sound_002"
#define SOUND_DEATH "sound_003"
#define SOUND_FOOTSTEP_LEFT_GRASS "sound_004"
#define SOUND_FOOTSTEP_RIGHT_GRASS "sound_005"
#define SOUND_FOOTSTEP_LEFT_CAVE "sound_006"
#define SOUND_FOOTSTEP_RIGHT_CAVE "sound_007"
#define SOUND_JUMP_SPRING "sound_008"
#define SOUND_LANDING_GRASS "sound_009"
#define SOUND_LANDING_CAVE "sound_010"
#define SOUND_SNAKE_DEATH "sound_011"
#define SOUND_TRIGGER_TRANSFORM "sound_012"
#define SOUND_CANCEL_TRANSFORM "sound_013"
#define SOUND_COMPLETE_TRANSFORM "sound_014"
#define SOUND_JUMP_SPRING_HEAVY "sound_015"
#define SOUND_JON_RABBIT_JUMP "sound_016"
#define SOUND_JON_VAMPIRE_JUMP "sound_017"
#define SOUND_JON_RABBIT_DOUBLE_JUMP "sound_018"
#define SOUND_JON_VAMPIRE_DOUBLE_JUMP "sound_019"
#define SOUND_JON_VAMPIRE_GLIDE "sound_020"
#define SOUND_MUSHROOM_BOUNCE "sound_021"
#define SOUND_JON_BURROW_ROCKSFALL "sound_022"
#define SOUND_SPARROW_FLY "sound_023"
#define SOUND_SPARROW_DEATH "sound_024"
#define SOUND_TOAD_DEATH "sound_025"
#define SOUND_TOAD_EAT "sound_026"
#define SOUND_SAW_GRIND "sound_027"
#define SOUND_FOX_BOUNCED_ON "sound_028"
#define SOUND_FOX_STRIKE "sound_029"
#define SOUND_FOX_DEATH "sound_030"
#define SOUND_WORLD_1_LOOP_INTRO "sound_031"
#define SOUND_MID_BOSS_LOOP_INTRO "sound_032"
#define SOUND_MID_BOSS_SWOOP_DOWN "sound_033"
#define SOUND_MID_BOSS_TREE_SMASH "sound_034"
#define SOUND_MID_BOSS_DEATH "sound_035"
#define SOUND_SCREEN_TRANSITION "sound_036"
#define SOUND_SCREEN_TRANSITION_2 "sound_037"
#define SOUND_LEVEL_COMPLETE "sound_038"
#define SOUND_TITLE_LIGHTNING_1 "sound_039"
#define SOUND_TITLE_LIGHTNING_2 "sound_040"
#define SOUND_ABILITY_UNLOCK "sound_041"
#define SOUND_BOSS_LEVEL_CLEAR "sound_042"
#define SOUND_LEVEL_CLEAR "sound_043"
#define SOUND_LEVEL_SELECTED "sound_044"
#define SOUND_RABBIT_DRILL "sound_045"
#define SOUND_SNAKE_JUMP "sound_046"
#define SOUND_VAMPIRE_DASH "sound_047"
#define SOUND_BOSS_LEVEL_UNLOCK "sound_048"
#define SOUND_RABBIT_STOMP "sound_049"
#define SOUND_END_BOSS_LOOP_INTRO "sound_050"
#define SOUND_BUTTON_CLICK "sound_051"
#define SOUND_LEVEL_CONFIRMED "sound_052"
#define SOUND_BAT_POOF "sound_053"
#define SOUND_CHAIN_SNAP "sound_054"
#define SOUND_END_BOSS_SNAKE_MOUTH_OPEN "sound_055"
#define SOUND_END_BOSS_SNAKE_CHARGE_CUE "sound_056"
#define SOUND_END_BOSS_SNAKE_CHARGE "sound_057"
#define SOUND_END_BOSS_SNAKE_DAMAGED "sound_058"
#define SOUND_END_BOSS_SNAKE_DEATH "sound_059"
#define SOUND_SPIKED_BALL_ROLLING "sound_060"
#define SOUND_ABSORB_DASH_ABILITY "sound_061"
#define SOUND_FOOTSTEP_LEFT_WOOD "sound_062"
#define SOUND_FOOTSTEP_RIGHT_WOOD "sound_063"
#define SOUND_LANDING_WOOD "sound_064"
#define SOUND_COLLECT_BIG_CARROT "sound_065"
#define SOUND_COLLECT_VIAL "sound_066"

//// Music Definitions ////

#define MUSIC_TITLE_LOOP "music_001"
#define MUSIC_OPENING_CUTSCENE "music_002"
#define MUSIC_LEVEL_SELECT_LOOP "music_003"
#define MUSIC_WORLD_1_LOOP "music_004"
#define MUSIC_WORLD_1_MID_BOSS_LOOP "music_005"
#define MUSIC_WORLD_1_END_BOSS_LOOP "music_006"

//// Texure Definitions ////

#define TEX_JON "texture_001"
#define TEX_MISC "texture_002"
#define TEX_TITLE "texture_003"
#define TEX_TRANS_DEATH_HELPER "texture_004"
#define TEX_TUTORIAL "texture_005"
#define TEX_VAMPIRE "texture_006"
#define TEX_WORLD_1_BG_LOWER_1 "texture_007"
#define TEX_WORLD_1_BG_LOWER_2 "texture_008"
#define TEX_WORLD_1_BG_MID "texture_009"
#define TEX_WORLD_1_BG_UPPER "texture_010"
#define TEX_WORLD_1_CUTSCENE_1 "texture_011"
#define TEX_WORLD_1_CUTSCENE_2 "texture_012"
#define TEX_WORLD_1_END_BOSS_1 "texture_013"
#define TEX_WORLD_1_END_BOSS_2 "texture_014"
#define TEX_WORLD_1_END_BOSS_3 "texture_015"
#define TEX_WORLD_1_ENEMIES "texture_016"
#define TEX_WORLD_1_GROUND "texture_017"
#define TEX_WORLD_1_MID_BOSS_1 "texture_018"
#define TEX_WORLD_1_MID_BOSS_2 "texture_019"
#define TEX_WORLD_1_MID_BOSS_3 "texture_020"
#define TEX_WORLD_1_OBJECTS_1 "texture_021"
#define TEX_WORLD_1_OBJECTS_2 "texture_022"
#define TEX_WORLD_1_SPECIAL "texture_023"
#define TEX_WORLD_MAP_1 "texture_024"
#define TEX_WORLD_MAP_2 "texture_025"
#define TEX_COMPRESSED_JON "texture_026"
#define TEX_COMPRESSED_TUTORIAL "texture_027"
#define TEX_COMPRESSED_VAMPIRE "texture_028"
#define TEX_COMPRESSED_WORLD_1_CUTSCENE_1 "texture_029"
#define TEX_COMPRESSED_WORLD_1_CUTSCENE_2 "texture_030"
#define TEX_COMPRESSED_WORLD_1_END_BOSS_1 "texture_031"
#define TEX_COMPRESSED_WORLD_1_END_BOSS_2 "texture_032"
#define TEX_COMPRESSED_WORLD_1_END_BOSS_3 "texture_033"
#define TEX_COMPRESSED_WORLD_1_ENEMIES "texture_034"
#define TEX_COMPRESSED_WORLD_1_GROUND "texture_035"
#define TEX_COMPRESSED_WORLD_1_MID_BOSS_1 "texture_036"
#define TEX_COMPRESSED_WORLD_1_MID_BOSS_2 "texture_037"
#define TEX_COMPRESSED_WORLD_1_MID_BOSS_3 "texture_038"
#define TEX_COMPRESSED_WORLD_1_OBJECTS_1 "texture_039"
#define TEX_COMPRESSED_WORLD_1_OBJECTS_2 "texture_040"
#define TEX_COMPRESSED_WORLD_1_SPECIAL "texture_041"
#define TEX_KEYBOARD_TUTORIAL "texture_042"
#define TEX_GAMEPAD_TUTORIAL "texture_043"
#define TEX_LEVEL_EDITOR "texture_044"

//// Shader Definitions ////

#define END_BOSS_FRAGMENT_SHADER "shader_004_frag"
#define FADE_SCREEN_FRAGMENT_SHADER "shader_005_frag"
#define OBFUSCATION_FRAGMENT_SHADER "shader_006_frag"
#define TINT_TO_SCREEN_FRAGMENT_SHADER "shader_007_frag"
#define POINT_TRANS_SCREEN_VERTEX_SHADER "shader_008_vert"
#define POINT_TRANS_SCREEN_FRAGMENT_SHADER "shader_008_frag"
#define RADIAL_BLUR_FRAGMENT_SHADER "shader_009_frag"
#define SHOCKWAVE_VERTEX_SHADER "shader_010_vert"
#define SHOCKWAVE_FRAGMENT_SHADER "shader_010_frag"
#define SNAKE_DEATH_FRAGMENT_SHADER "shader_011_frag"
#define TRANS_DEATH_IN_FRAGMENT_SHADER "shader_012_frag"
#define TRANS_DEATH_OUT_FRAGMENT_SHADER "shader_013_frag"
#define TRANS_SCREEN_FRAGMENT_SHADER "shader_014_frag"

//// Render Definitions ////

#define MAX_BATCH_SIZE 16384

//// Texture Definitions ////

#define PIXEL_WIDTH_FOR_GAME 1808
#define PIXEL_HEIGHT_FOR_GAME 4096

//// Matrix Definitions ////

#define CAM_WIDTH 15.890625f
#define CAM_HEIGHT 9.0f

//// Touch Input Definitions ////

#define SWIPE_WIDTH CAM_WIDTH / 32
#define SWIPE_HEIGHT CAM_HEIGHT / 18

//// World Definitions ////

#define GRID_CELL_SIZE 0.140625f

#define ZOOMED_OUT_CAM_WIDTH 63.5625f
#define GAME_HEIGHT 36.0f

#define GAME_GRAVITY -18.0f

#define RABBIT_DEFAULT_MAX_SPEED 7.5f
#define RABBIT_DEFAULT_ACCELERATION 5.0f
#define VAMP_DEFAULT_MAX_SPEED 11.0f
#define VAMP_DEFAULT_ACCELERATION 7.0f

#define SCORE_ENEMY 2500
#define SCORE_CARROT 250
#define SCORE_GOLDEN_CARROT 10000
#define SCORE_BIG_CARROT 2500
#define SCORE_VIAL 25000

//// Flag Level Definitions ////

#define FLAG_LEVEL_COMPLETE 1
#define FLAG_FIRST_GOLDEN_CARROT_COLLECTED 2
#define FLAG_SECOND_GOLDEN_CARROT_COLLECTED 4
#define FLAG_THIRD_GOLDEN_CARROT_COLLECTED 8
#define FLAG_BONUS_GOLDEN_CARROT_COLLECTED 16
#define FLAG_LEVEL_UNLOCKED 32

//// Flag Ability Definitions ////

#define FLAG_ABILITY_RABBIT_RIGHT 1
#define FLAG_ABILITY_RABBIT_UP 2
#define FLAG_ABILITY_RABBIT_LEFT 4
#define FLAG_ABILITY_RABBIT_DOWN 8
#define FLAG_ABILITY_VAMPIRE_RIGHT 16
#define FLAG_ABILITY_VAMPIRE_UP 32
#define FLAG_ABILITY_VAMPIRE_LEFT 64
#define FLAG_ABILITY_VAMPIRE_DOWN 128
#define FLAG_ABILITY_DOUBLE_JUMP 256
#define FLAG_ABILITY_TRANSFORM 512

#define FLAG_ABILITY_ALL 1023

//// Flag Cutscene Definitions ////

#define FLAG_CUTSCENE_VIEWED_OPENING 1

//// Render Definitions ////

#define NUM_FRAMEBUFFERS 4

#endif /* defined(__nosfuratu__GameConstants__) */
