//
//  GroundType.h
//  nosfuratu
//
//  Created by Stephen Gowen on 9/22/15.
//  Copyright © 2015 Gowen Game Dev. All rights reserved.
//

#ifndef __nosfuratu__GroundType__
#define __nosfuratu__GroundType__

typedef enum
{
    GROUND_GRASS_WITH_CAVE_LARGE,
    GROUND_CAVE_LARGE,
    GROUND_GRASS_WITHOUT_CAVE_LARGE,
    GROUND_GRASS_WITHOUT_CAVE_END_LEFT,
    GROUND_GRASS_WITHOUT_CAVE_MEDIUM,
    GROUND_GRASS_WITHOUT_CAVE_SMALL,
    GROUND_GRASS_WITHOUT_CAVE_END_RIGHT,
    GROUND_GRASS_WITH_CAVE_END_LEFT,
    GROUND_GRASS_WITH_CAVE_MEDIUM,
    GROUND_GRASS_WITH_CAVE_SMALL,
    GROUND_GRASS_WITH_CAVE_END_RIGHT,
    GROUND_CAVE_END_LEFT,
    GROUND_CAVE_MEDIUM,
    GROUND_CAVE_SMALL,
    GROUND_CAVE_END_RIGHT,
    GROUND_CAVE_RAISED_END_LEFT,
    GROUND_CAVE_RAISED_MEDIUM,
    GROUND_CAVE_RAISED_SMALL,
    GROUND_CAVE_RAISED_END_RIGHT,
    GROUND_CAVE_RAISED_LARGE
} GroundType;

#endif /* defined(__nosfuratu__GroundType__) */
